"""Ton address has been added to withdraw requests

Revision ID: 179e15d85a47
Revises: 1ceba9cf572d
Create Date: 2025-05-18 23:19:49.860514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179e15d85a47'
down_revision: Union[str, None] = '1ceba9cf572d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('ton_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawals', 'ton_address')
    # ### end Alembic commands ###
