"""Added is_vip variable for promocode

Revision ID: 28a6087dba63
Revises: c51d15ac03b9
Create Date: 2025-06-03 00:34:21.341251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a6087dba63'
down_revision: Union[str, None] = 'c51d15ac03b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_codes', sa.Column('is_vip', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_codes', 'is_vip')
    # ### end Alembic commands ###
