"""Added required subscription field to channels

Revision ID: 690d5cb4e66d
Revises: 28a6087dba63
Create Date: 2025-06-09 18:41:08.189004

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "690d5cb4e66d"
down_revision: Union[str, None] = "28a6087dba63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channels", sa.Column("requires_subscription", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "requires_subscription")
    # ### end Alembic commands ###
