"""Added new field max activations to promo codes

Revision ID: 7ab65628eb21
Revises: f76506ca4a7d
Create Date: 2025-05-10 03:36:24.360476

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ab65628eb21"
down_revision: Union[str, None] = "f76506ca4a7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "promo_codes", sa.Column("max_activations", sa.Integer(), nullable=False)
    )
    op.add_column(
        "promo_codes", sa.Column("activations_left", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promo_codes", "activations_left")
    op.drop_column("promo_codes", "max_activations")
    # ### end Alembic commands ###
