"""Deposit functionality added

Revision ID: 8bc0d7bdd539
Revises: e1ebb1c8ce9c
Create Date: 2025-05-20 03:57:29.569219

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bc0d7bdd539"
down_revision: Union[str, None] = "e1ebb1c8ce9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("stars", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("ton", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", name="depositstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deposits")
    # ### end Alembic commands ###
