"""Game settings table has been added

Revision ID: e1ebb1c8ce9c
Revises: 179e15d85a47
Create Date: 2025-05-19 19:07:14.634336

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1ebb1c8ce9c"
down_revision: Union[str, None] = "179e15d85a47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.add_column(
        "daily_bonus_claims",
        sa.Column("streak", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_bonus_claims", "streak")
    op.drop_table("game_settings")
    # ### end Alembic commands ###
