"""Updated giveaway model

Revision ID: ee7a120aa69a
Revises: 28d205f1bc55
Create Date: 2025-06-13 20:12:49.809675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7a120aa69a'
down_revision: Union[str, None] = '28d205f1bc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('channel_link', sa.String(), nullable=True))
    op.add_column('giveaways', sa.Column('num_of_winners', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giveaways', 'num_of_winners')
    op.drop_column('giveaways', 'channel_link')
    # ### end Alembic commands ###
