"""New 2XGame added

Revision ID: 954461272dc1
Revises: 2f2a3d3cc053
Create Date: 2025-05-15 03:43:37.213849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954461272dc1'
down_revision: Union[str, None] = '2f2a3d3cc053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('x2game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('won', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('x2game')
    # ### end Alembic commands ###
