"""Changed is_vip nullable to false

Revision ID: a48d281b2e58
Revises: 19a1d3634b1d
Create Date: 2025-05-07 14:58:17.958917

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a48d281b2e58"
down_revision: Union[str, None] = "19a1d3634b1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_vip", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_vip", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
